version: "3.8"

services:
  db:
    image: "mysql:8.0"
    container_name: "db"
    ports:
      - 3306:3306
    environment:
      MYSQL_USERNAME: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: "test"
      MYSQL_ROOT_PASSWORD: "root"
